language: c

sudo: false

env:
    - DOTFILES_ROOT="$(readlink -m "../${PWD}")"

before_script:
    - git clone https://github.com/sstephenson/bats.git

script:
    - bin/bats --tap ./test

notifications:
    email:
        on_success: never
