language: c

sudo: false

env:
    - BASH_COMPAT=31
    - BASH_COMPAT=41
    - BASH_COMPAT=43
    - BASH_COMPAT=

before_script:
    - git clone https://github.com/sstephenson/bats.git

script:
    - ./bats/bin/bats --tap ./test

notifications:
    email:
        on_success: never
